version: '2'

services:
  api:
    image: 'docker-spring-boot-postgres:latest'
    build:
      dockerfile: Dockerfile
      context: .
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      .env
  web:
    image: nginx
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "80:80"
    links:
      - api
  db:
    image: 'postgres'
    container_name: db
    user: postgres
    env_file:
      .env
    ports:
      - "5432:8080"
    # The Postgres Admin tool if we want to run some custom queries and so on against our Database
  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8080"


